name: Tests

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  pre-commit:
    name: "pre-commit checks"
    uses: pcdshub/pcds-ci-helpers/.github/workflows/pre-commit.yml@master
    with:
      args: "--all-files"
